development:
  adapter: postgresql
  encoding: utf8
  database: proficiency-test_development
  pool: 5
  username: postgres
  password: 123456
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: proficiency-test_test
  pool: 5
  username: postgres
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: proficiency-test_production
  pool: 5
  username: postgres
  password: 123456
  host: localhost